APP_ERROR_CODES = {
  # Authentication
  4010 => "UNAUTHENTICATED",
  4011 => "INVALID_TOKEN",
  4012 => "ACCOUNT_LOCKED",

  # Authorization
  4030 => "ACCESS_FORBIDDEN_BY_POLICY",
  4031 => "ACCESS_FORBIDDEN_BY_ROLE_PERMISSION",
}.freeze
